"""Client-side constants for RiftTalk."""

SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE
SECONDS_PER_DAY = 24 * SECONDS_PER_HOUR

MATCH_STATUS_REMOTE_REFRESH_SECONDS = 90

MATCH_INFO_TTL_SECONDS = SECONDS_PER_HOUR
USER_SESSION_TTL_SECONDS = 7 * SECONDS_PER_DAY
DISCORD_LINK_TTL_SECONDS = 30 * SECONDS_PER_DAY

REMOTE_API_TIMEOUT_SECONDS = 15
REMOTE_API_HEALTH_TIMEOUT_SECONDS = 10

MATCH_NOTIFY_RETRY_BASE_SECONDS = 5
MATCH_NOTIFY_RETRY_MAX_SECONDS = 300

SHUTDOWN_MATCH_LEAVE_TIMEOUT_SECONDS = 5
