"""Server-side constants for RiftTalk."""

SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE
SECONDS_PER_DAY = 24 * SECONDS_PER_HOUR

DISCORD_LINK_TTL_SECONDS = 30 * SECONDS_PER_DAY
DISCORD_INVITE_TTL_SECONDS = SECONDS_PER_HOUR
USER_MATCH_TTL_SECONDS = SECONDS_PER_HOUR

MATCH_START_DEBOUNCE_SECONDS = 10
ROOM_CREATE_LOCK_TTL_SECONDS = 30
ROOM_CREATE_WAIT_ATTEMPTS = 10
ROOM_CREATE_WAIT_SLEEP_SECONDS = 0.1

RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_KEY_TTL_SECONDS = 120

DISCORD_OAUTH_HTTP_TIMEOUT_SECONDS = 10
REQUEST_RETRY_MAX_ATTEMPTS = 3
REQUEST_RETRY_BACKOFF_START_SECONDS = 1
REQUEST_RETRY_BACKOFF_MAX_SECONDS = 8

DISCORD_GC_INTERVAL_MINUTES = 30
