"""Shared constants for RiftTalk."""

SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE

DEFAULT_ROOM_TTL_SECONDS = SECONDS_PER_HOUR
DEFAULT_USER_MATCH_TTL_SECONDS = SECONDS_PER_HOUR

REDIS_RECONNECT_INTERVAL_SECONDS = 5
